### ISSUE TITLE
Check that kalc will not move singleton pod (a single pod deployment) when draining a node

### ISSUE THREAD

**Issue by grandrew** [criticalhop/kalc#114]
Currently, kalc can move any pods, including ones that are singletons in a deployment. 

Because we can not yet know whether these pods can functions in multiple replicas - we can not move them until information is available about whether scaling of these pods is allowed

- [x] do not move pods with Deployment and replicas=1
- [x] do not move pods that have no Deployment

done in 6192d7f31a93aba85eef116285808e25b2b6d626

**Comment by makarty** [comment]
done in 6192d7f
