### ISSUE TITLE
Test for changed cluster state

### ISSUE THREAD

**Issue by grandrew** [criticalhop/kalc#124]
In move/apply script, check if state has diverged too far and we can not continue

- [ ] store cluster state in format of kubectl wide with fields pod, node, sorted by pod name
- [ ] store this information in the script
- [ ] calculate md5 of cluster state
- [ ] do kubectl get wide, calculate md5
- [ ] compare the sums
- [ ] emit warning when running script if the state has diverged

**Comment by grandrew** [comment]
- [ ] To get current cluster state "snapshot", use smth like this: `kubectl get pods -o wide --sort-by="{.spec.nodeName}" | md5sum`
- [ ] Store this value BEFORE running update()
- [ ] Store this value somewhere when you can then add to final bash script
- [ ] In bash script, check with `$(kubectl get pods -o wide --sort-by="{.spec.nodeName}" | md5sum) == "{md5sum_stored}"` in file header. 
- [ ] Add as a parameter to `generate_compat_header` function
- [ ] Allow to work without this parameter (default to None and don't check)
- [ ] Write `WARNING: CLUSTER STATE DIVERGED - USE AT YOUR OWN RISK` as comment and in `echo` in script

**Comment by andreykyz** [comment]
md5 for state : 

`kubectl get pods -o wide --sort-by="{.spec.nodeName}" | awk ' {print $1,$2,$3,$6,$7} ' | md5sum`
