### ISSUE TITLE
Unresolved import in Kalc

### ISSUE THREAD

**Issue by andreykyz** [criticalhop/kalc#129]
branch develop , transition-merge

> ImportError while importing test module '/home/andrey/sandbox/ch/kalc/tests/test_vu.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> .tox/poodledev/lib/python3.7/site-packages/_pytest/python.py:493: in _importtestmodule
>     mod = self.fspath.pyimport(ensuresyspath=importmode)
> .tox/poodledev/lib/python3.7/site-packages/py/_path/local.py:701: in pyimport
>     __import__(modname)
> .tox/poodledev/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:143: in exec_module
>     exec(co, module.__dict__)
> tests/test_vu.py:1: in <module>
>     from kalc.misc.cli_optimize import optimize_cluster
> kalc/misc/cli_optimize.py:1: in <module>
>     from kalc.interactive import *
> kalc/interactive.py:4: in <module>
>     from kalc.model.full import kinds_collection
> kalc/model/full.py:12: in <module>
>     module = __import__(modname, fromlist="dummy")
> kalc/model/kinds/DaemonSet.py:5: in <module>
>     from kalc.model.kinds.Node import Node
> kalc/model/kinds/Node.py:9: in <module>
>     from kalc.model.scenario import ScenarioStep, describe
> E   ModuleNotFoundError: No module named 'kalc.model.scenario'
>

**Comment by grandrew** [comment]
scenario and ScenarioStep where completely removed.

Probably references still exist somewhere
