### ISSUE TITLE
Develop optimization formula

### ISSUE THREAD

**Issue by makarty** [criticalhop/kalc#185]
Simple formula for poodle

- [ ] balance stability/compactness
- [ ] oversubscription
- [ ] new pods/stable pods

**Comment by grandrew** [comment]
Optimization formula is now called "Weighted count of violated policies (w-CVP)  method"

and we're pareto-optimizing it

set to implement for next milestone

Example of policy violations and how to count them:

1. f node utilization > 60%: +1 bad
    2. > 70%: +2 bad
3. If node < 30% : +1 bad
4. If pod is new, and is on same node with stable old pod: +1 bad
5. If pod of one deployment on node with other pod, add +1, +2 ,etc. for every pod of this deployment on one node
