### ISSUE TITLE
Scenario Story: User can find all scenarios if user doesn't know which service to check

### ISSUE THREAD

**Issue by makarty** [criticalhop/kalc#25]
When a user doesn't know what which service he wants to check he may find all possible failure scenarios (if needed).
To achieve this user finds one scenario< then excludes found service from search and starts to search for another service and repeats this operation as many times as required to make sure all important services are checked.

Usage:
`-e "Service:redis-master-evict"`, `--ignore-nonexistent-exclusions`

Add keys:

`-e`, `--exclude` - how to use: `-e "Service:redis-master-evict"` which is -e `<Kind>:<name>`

to do many exclusions:

`-e "Service:redis-master,Service:heapster"`

Definition of done:

## 1. Find correct scenario

```shell
kubectl-val -d tests/daemonset_eviction/cluster_dump -f tests/daemonset_eviction/daemonset_create.yaml -e "Service:redis-master,Service:heapster"
```

must return eviction scenario for `redis-master-evict`

## 2. Complain about non-existing names for exclustion

```shell
kubectl-val -d tests/daemonset_eviction/cluster_dump -f tests/daemonset_eviction/daemonset_create.yaml -e "Service:redis-muster,Service:heapster"
```

must return `Error: no such Service: 'redis-muster'` (can be done using Python exception)

## 3. Do not complain if an option is set:

`--ignore-nonexistent-exclusions` (no short form!)

## 4. Complain about non-existing Types:
```shell
kubectl-val -d tests/daemonset_eviction/cluster_dump -f tests/daemonset_eviction/daemonset_create.yaml -e "Service:redis-master,ServUce:heapster"
```

must return  "Error: no such type 'ServUce'"

**Comment by andreykyz** [comment]
## 4. Complain about non-existing Types:
kubectl-val -d tests/daemonset_eviction/cluster_dump -f tests/daemonset_eviction/daemonset_create.yaml -e "Service:redis-master,ServUce:heapster"
must return  "Error: no such type 'ServUce'"
